permissions:
  # Needed to access the workflow's OIDC identity.
  id-token: write

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  staging-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a
      - name: staging-tests
        run: |
          pip install sigstore
          echo "hello" > hello.txt
          python -m sigstore sign hello.txt
          openssl x509 -noout -text -in hello.txt.crt
